In [1]:
import numpy
world_alcohol = numpy.genfromtxt("world_alcohol.txt",delimiter = ",",dtype = str,skip_header = 0)
print(type(world_alcohol))
print(world_alcohol)
print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
[['0-0' ' 0-1' '0-2' '0']
 ['1-0' '1-1' '1-2 ' '1']
 ['2-0' '2-1' '2-2 ' '2']
 ['0   ' '1   ' ' 2 ' '   3']]
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is 

In [2]:
vector = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30],[42,145,134]])
print(type(vector.shape))
print(vector.shape)
print(matrix.shape)

<class 'tuple'>
(4,)
(3, 3)


In [3]:
numbers = numpy.array([1,2,3,4])
numbers1 = numpy.array([1,2,3,4.0])
print(numbers.dtype)
print(numbers1.dtype)

int32
float64


In [4]:
print(world_alcohol[1,0])
world_alcohol[2,2]

1-0


'2-2 '

In [5]:
print(world_alcohol[2][0:2])
print(world_alcohol[:,2])
print(world_alcohol[2:4,1:4])

['2-0' '2-1']
['0-2' '1-2 ' '2-2 ' ' 2 ']
[['2-1' '2-2 ' '2']
 ['1   ' ' 2 ' '   3']]


In [6]:
print(vector)
vector == 10

[ 5 10 15 20]


array([False,  True, False, False])

In [7]:
print(matrix)
temp = (matrix == 25)
print(temp)
print(temp.dtype)
#找出包含了25的一行
print(matrix[temp[:,1],:])

[[  5  10  15]
 [ 20  25  30]
 [ 42 145 134]]
[[False False False]
 [False  True False]
 [False False False]]
bool
[[20 25 30]]


In [8]:
print(vector)
temp = ((vector == 5) & (vector == 10))
print(temp)
temp = ((vector == 15) | (vector == 20))
print(temp)
vector[temp] = 30
print(vector)

[ 5 10 15 20]
[False False False False]
[False False  True  True]
[ 5 10 30 30]


In [23]:
vector = numpy.array(["8","1","18","2","3"])
vector1 = vector.astype(float)
print(vector1)
print("mininum = %d max = %d " %(vector1.min(),vector1.max()))

[ 8.  1. 18.  2.  3.]
mininum = 1 max = 18 


In [34]:
print(matrix)
#行求和
print(matrix.sum(axis = 1))
print("列求和:")
print(matrix.sum(axis = 0))
matrix.ndim
https://www.bilibili.com/video/av31488867/?p=11
P11

SyntaxError: invalid syntax (<ipython-input-34-458e7d65cd7f>, line 7)